### ISSUE TITLE
retry_delay being set results in no retry

### ISSUE THREAD

**Issue by Cervenka** [lantins/resque-retry#113] opened 2014-11-24 14:29 UTC
Hi,
I tried using following parameters:
@retry_limit = 3
@retry_delay = 5

No retries are being run in that case.
If I do not set @retry_delay the retries are executed as expected.

I also tried using the default exponential backoff example. Any value higher than 0 results in no retries to be executed.

So any delay causes no retries to be executed.

Did I misconfigure something? Thank you.

**Comment by anujbiyani** [comment] 2015-02-19 18:51
+1

setting `@retry_delay = 0` works, but setting it to something greater than 0 resulted in no retries.

**Comment by julienXX** [comment] 2015-02-23 15:54
I can see that too.

**Comment by jzaleski** [comment] 2015-02-23 18:36
It looks like you may have stumbled across a bug/regression @Cervenka! If you guys (@anujbiyani & @julienXX included) want to take a stab at writing a failing test-case and submit a pull-request for a fix I will help you to get it merged. Thanks guys!

**Comment by julienXX** [comment] 2015-02-23 19:43
Will try to submit something :)

**Comment by jzaleski** [comment] 2015-02-24 16:45
Sounds great! Thank you

**Comment by mindware** [comment] 2015-05-13 05:02
Any progress on this?

**Closed** 2015-08-04 01:53 UTC

**Comment by cbelsole** [comment] 2015-11-12 20:43
I am still seeing this error.

**Comment by jzaleski** [comment] 2015-11-12 22:57
Can you please provide the steps to reproduce?
